### ISSUE TITLE
iPad Safari: tapping anywhere in the modal closes it

### ISSUE THREAD

**Issue by curagea** [awkward/backbone.modal#71] opened 2015-04-08 01:04 UTC
Every time I tap on the modal, regardless of the element I'm tapping on, the modal would close. If I tap on an input, the iOS keyboard would show up briefly before the modal closes. I've traced this down to `clickOutside`, where the event target ends up as the modal wrapper, and thus `triggerCancel` is called.

iOS 8.1.3 and up is affected.

**Comment by davidvanleeuwen** [comment] 2015-04-25 17:57
I think this is related to some CSS problem in your project, because when trying out the examples on an iPad it simply works. Could you maybe share something you have?

**Comment by curagea** [comment] 2015-04-25 19:56
I've tried out the examples on my iPad, and they show the same bug.

**Comment by mobutils** [comment] 2015-05-05 22:26
I can confirm this issue, tested out on iPad Mini / iPad 2. iOS 8.0.3... I have keyControl turned off so it on the 1st modal the user interacts with. It appears that the wrapper container is appearing above the content of modal, thus when you click links / input elements it doesn't do anything... (if keyControl is turned off the modal closes).... this also affects the demo modal on your website. (can't click the links within the modal on iPad)...

**Comment by davidvanleeuwen** [comment] 2015-05-07 21:22
Thanks guys :sparkles: !

Fixed in the master right now, check #77

**Closed by davidvanleeuwen** 2015-05-07 21:22 UTC
