### ISSUE TITLE
Add CSS classes to the created element in the modal?

### ISSUE THREAD

**Issue by george-silva** [awkward/backbone.modal#79] opened 2015-05-20 18:39 UTC
I want to have variable width modals. I can configure them in the view, using the className property. But that is applied to the bbm-wrapper element.

Is it possible to configure a class to be dinamically in the div that comes with bbm-modal class?

**Comment by zeakd** [comment] 2015-08-13 07:36
The problem is, setting className on BackBone.Modal is adding them to '.bbm-wrapper', not .bbm-modal. 
I solved it just adding '.bbm-modal-{{size}}' on modalEl
``` js
onRender: function () {
    this.modalEl.addClass('bbm-modal-large')
}
```
``` css
.bbm-modal {
  max-width: none;
}
.bbm-modal-large {
  width : 980px;
}
```

**Comment by jimf** [comment] 2017-10-03 02:27
Closing due to age, but feel free to reopen. I'd recommend `onRender` as well though.

**Closed by jimf** 2017-10-03 02:27 UTC
